const jwt = require("jsonwebtoken")

const authentication = async function (req, res, next) {
  try {
    //setting token in the request header.
    const token = req.header('Authorization')

    if (!token) {
      return res.status(403).send({ status: false, message: `Missing authentication token in request` })
    }

    tokenNew = token.split(' ')
    let requiredToken = tokenNew[1]

    //decoding authentication token
    const decoded = jwt.verify(requiredToken, 'Uranium Project-5'); 

    if (!decoded) {
      return res.status(400).send({ status: false, message: "Invalid authentication token in request headers." })
    }
    //console.log(decoded)
    //matching userId for which token generated by the userId provided in the request.
    req.userId = decoded.userID;
    //console.log(req.userId)
    next()

  }
  catch (error) {
    return res.status(500).send({ status: false, message: error.message })
  }
}


module.exports.authentication = authentication;